baseURL = 'https://leoniekaiser.com/'
languageCode = 'de-at'
defaultContentLanguage = 'de'
title = 'Leonie Kaiser – KI & Business Consulting'

enableRobotsTXT = true
enableEmoji = true

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ['HTML']

[imaging]
  quality = 82
  resampleFilter = 'Lanczos'

[minify]
  minifyOutput = true
