baseURL = 'https://leoniekaiser.com/'
languageCode = 'de-AT'
defaultContentLanguage = 'de'
title = 'KI-Beraterin Wien – Strategie & EU AI Act | Leonie Kaiser'

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

disableKinds = ["taxonomy", "term"]

[markup.goldmark.renderer]
  unsafe = true

[permalinks]
  journal = "/blog/:slug/"

[outputs]
  home = ['HTML','RSS']

[imaging]
  quality = 82
  resampleFilter = 'Lanczos'

[minify]
  minifyOutput = true

[sitemap]
  changefreq = 'monthly'
  priority = 0.7
  filename = 'sitemap.xml'
